name: 'Publish Prerequisites'
description: 'Perform any operations that are required when the packages are being published.'

inputs:
  package:
    description: 'The package to publish prerequisites for.'
    required: true
    default: 'all'
  publish-config-json:
    description: 'The configuration to use when publishing, stored as JSON.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Write publish-config.json
      shell: bash
      run: |
        echo '${{ inputs.publish-config-json }}' > packages/synchronised-storage-service/scripts/publish-config.json

    - name: Setup sync storage for mainnet
      shell: bash
      run: |
        cd packages/synchronised-storage-service
        node script/setup-sync-storage.mjs ./scripts/publish-config.json mainnet

    - name: Setup sync storage for testnet
      shell: bash
      run: |
        cd packages/synchronised-storage-service
        node script/setup-sync-storage.mjs ./scripts/publish-config.json testnet

    - name: Setup sync storage for devnet
      shell: bash
      run: |
        cd packages/synchronised-storage-service
        node script/setup-sync-storage.mjs ./scripts/publish-config.json devnet
