// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@twin.org/data-core";
import * as external0 from "../models/syncChangeOperation.js";
const MESSAGES = ["must be equal to constant","must be string","must be object","must be array"];
function createError(instancePath, schemaPath, keyword, params, message) {
return { instancePath, schemaPath, keyword, params, ["message"]: typeof message === "number" ? MESSAGES[message] : message };
}
function pushError(errors, error) {
if (errors === null) {
return [error];
}
errors.push(error);
return errors;
}
/**
 * Compiled validator for the SyncRequest schema.
 */
export const CompiledSyncRequest: ICompiledValidator = validate52;

function validate52(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/synchronised-storage/SyncRequest" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate52.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@context"},"must have required property '"+"@context"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.type === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "type"},"must have required property '"+"type"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.nodeIdentity === undefined){
const err2 = createError(instancePath,"#/required","required",{missingProperty: "nodeIdentity"},"must have required property '"+"nodeIdentity"+"'");
vErrors = pushError(vErrors, err2);
errors++;
}
if(data["@context"] !== undefined){
if("https://schema.twindev.org/synchronised-storage/" !== data["@context"]){
const err3 = createError(instancePath+"/@context","#/properties/%40context/const","const",{allowedValue: "https://schema.twindev.org/synchronised-storage/"},0);
vErrors = pushError(vErrors, err3);
errors++;
}
}
if(data.type !== undefined){
if("SyncRequest" !== data.type){
const err4 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "SyncRequest"},0);
vErrors = pushError(vErrors, err4);
errors++;
}
}
if(data.nodeIdentity !== undefined){
if(typeof data.nodeIdentity !== "string"){
const err5 = createError(instancePath+"/nodeIdentity","#/properties/nodeIdentity/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err5);
errors++;
}
}
}
else {
const err6 = createError(instancePath,"#/type","type",{type: "object"},2);
vErrors = pushError(vErrors, err6);
errors++;
}
validate52.errors = vErrors;
return errors === 0;
}
validate52.evaluated = {"props":{"@context":true,"type":true,"nodeIdentity":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the SyncChangeSet schema.
 */
export const CompiledSyncChangeSet: ICompiledValidator = validate53;
const keyword0 = Object.values(external0["SyncChangeOperation"]);

function validate55(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/synchronised-storage/SyncChangeOperation" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate55.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!keyword0.includes(data)){
for(let i0 = 0; i0 < keyword0.length; i0++){
vErrors = pushError(vErrors, createError(instancePath, "#/anyOf" + "/" + i0 + "/const", "const", { allowedValue: keyword0[i0] }, "must be equal to constant"));
errors++;
}
vErrors = pushError(vErrors, createError(instancePath, "#/anyOf", "anyOf", {}, "must match a schema in anyOf"));
errors++;
}
validate55.errors = vErrors;
return errors === 0;
}
validate55.evaluated = {"dynamicProps":false,"dynamicItems":false};


function validate57(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/synchronised-storage/SynchronisedEntityCore" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate57.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.dateModified === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "dateModified"},"must have required property '"+"dateModified"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.dateModified !== undefined){
if(typeof data.dateModified !== "string"){
const err1 = createError(instancePath+"/dateModified","#/properties/dateModified/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err1);
errors++;
}
}
}
else {
const err2 = createError(instancePath,"#/type","type",{type: "object"},2);
vErrors = pushError(vErrors, err2);
errors++;
}
validate57.errors = vErrors;
return errors === 0;
}
validate57.evaluated = {"props":{"dateModified":true},"dynamicProps":false,"dynamicItems":false};


function validate54(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/synchronised-storage/SyncChange" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate54.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.operation === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "operation"},"must have required property '"+"operation"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.id === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "id"},"must have required property '"+"id"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.operation !== undefined){
if(!(validate55(data.operation, {instancePath:instancePath+"/operation",parentData:data,parentDataProperty:"operation",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate55.errors : vErrors.concat(validate55.errors);
errors = vErrors.length;
}
}
if(data.id !== undefined){
if(typeof data.id !== "string"){
const err2 = createError(instancePath+"/id","#/properties/id/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err2);
errors++;
}
}
if(data.entity !== undefined){
if(!(validate57(data.entity, {instancePath:instancePath+"/entity",parentData:data,parentDataProperty:"entity",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate57.errors : vErrors.concat(validate57.errors);
errors = vErrors.length;
}
}
}
else {
const err3 = createError(instancePath,"#/type","type",{type: "object"},2);
vErrors = pushError(vErrors, err3);
errors++;
}
validate54.errors = vErrors;
return errors === 0;
}
validate54.evaluated = {"props":{"operation":true,"id":true,"entity":true},"dynamicProps":false,"dynamicItems":false};


function validate53(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/synchronised-storage/SyncChangeSet" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate53.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@context"},"must have required property '"+"@context"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.type === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "type"},"must have required property '"+"type"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.id === undefined){
const err2 = createError(instancePath,"#/required","required",{missingProperty: "id"},"must have required property '"+"id"+"'");
vErrors = pushError(vErrors, err2);
errors++;
}
if(data.storageKey === undefined){
const err3 = createError(instancePath,"#/required","required",{missingProperty: "storageKey"},"must have required property '"+"storageKey"+"'");
vErrors = pushError(vErrors, err3);
errors++;
}
if(data.dateCreated === undefined){
const err4 = createError(instancePath,"#/required","required",{missingProperty: "dateCreated"},"must have required property '"+"dateCreated"+"'");
vErrors = pushError(vErrors, err4);
errors++;
}
if(data.dateModified === undefined){
const err5 = createError(instancePath,"#/required","required",{missingProperty: "dateModified"},"must have required property '"+"dateModified"+"'");
vErrors = pushError(vErrors, err5);
errors++;
}
if(data.nodeIdentity === undefined){
const err6 = createError(instancePath,"#/required","required",{missingProperty: "nodeIdentity"},"must have required property '"+"nodeIdentity"+"'");
vErrors = pushError(vErrors, err6);
errors++;
}
if(data.changes === undefined){
const err7 = createError(instancePath,"#/required","required",{missingProperty: "changes"},"must have required property '"+"changes"+"'");
vErrors = pushError(vErrors, err7);
errors++;
}
if(data["@context"] !== undefined){
if("https://schema.twindev.org/synchronised-storage/" !== data["@context"]){
const err8 = createError(instancePath+"/@context","#/properties/%40context/const","const",{allowedValue: "https://schema.twindev.org/synchronised-storage/"},0);
vErrors = pushError(vErrors, err8);
errors++;
}
}
if(data.type !== undefined){
if("SyncChangeSet" !== data.type){
const err9 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "SyncChangeSet"},0);
vErrors = pushError(vErrors, err9);
errors++;
}
}
if(data.id !== undefined){
if(typeof data.id !== "string"){
const err10 = createError(instancePath+"/id","#/properties/id/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err10);
errors++;
}
}
if(data.storageKey !== undefined){
if(typeof data.storageKey !== "string"){
const err11 = createError(instancePath+"/storageKey","#/properties/storageKey/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err11);
errors++;
}
}
if(data.dateCreated !== undefined){
if(typeof data.dateCreated !== "string"){
const err12 = createError(instancePath+"/dateCreated","#/properties/dateCreated/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err12);
errors++;
}
}
if(data.dateModified !== undefined){
if(typeof data.dateModified !== "string"){
const err13 = createError(instancePath+"/dateModified","#/properties/dateModified/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err13);
errors++;
}
}
if(data.nodeIdentity !== undefined){
if(typeof data.nodeIdentity !== "string"){
const err14 = createError(instancePath+"/nodeIdentity","#/properties/nodeIdentity/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err14);
errors++;
}
}
if(data.changes !== undefined){
let data7 = data.changes;
if(Array.isArray(data7)){
const len0 = data7.length;
for(let i0=0; i0<len0; i0++){
if(!(validate54(data7[i0], {instancePath:instancePath+"/changes/" + i0,parentData:data7,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate54.errors : vErrors.concat(validate54.errors);
errors = vErrors.length;
}
}
}
else {
const err15 = createError(instancePath+"/changes","#/properties/changes/type","type",{type: "array"},3);
vErrors = pushError(vErrors, err15);
errors++;
}
}
}
else {
const err16 = createError(instancePath,"#/type","type",{type: "object"},2);
vErrors = pushError(vErrors, err16);
errors++;
}
validate53.errors = vErrors;
return errors === 0;
}
validate53.evaluated = {"props":{"@context":true,"type":true,"id":true,"storageKey":true,"dateCreated":true,"dateModified":true,"nodeIdentity":true,"changes":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the SyncChange schema.
 */
export const CompiledSyncChange: ICompiledValidator = validate54;

/**
 * Compiled validator for the SynchronisedEntity schema.
 */
export const CompiledSynchronisedEntity: ICompiledValidator = validate60;

function validate60(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/synchronised-storage/SynchronisedEntity" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate60.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(validate57(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate57.errors : vErrors.concat(validate57.errors);
errors = vErrors.length;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.id === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "id"},"must have required property '"+"id"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.nodeIdentity === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "nodeIdentity"},"must have required property '"+"nodeIdentity"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.id !== undefined){
if(typeof data.id !== "string"){
const err2 = createError(instancePath+"/id","#/properties/id/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err2);
errors++;
}
}
if(data.nodeIdentity !== undefined){
if(typeof data.nodeIdentity !== "string"){
const err3 = createError(instancePath+"/nodeIdentity","#/properties/nodeIdentity/type","type",{type: "string"},1);
vErrors = pushError(vErrors, err3);
errors++;
}
}
}
else {
const err4 = createError(instancePath,"#/type","type",{type: "object"},2);
vErrors = pushError(vErrors, err4);
errors++;
}
validate60.errors = vErrors;
return errors === 0;
}
validate60.evaluated = {"props":{"id":true,"nodeIdentity":true,"dateModified":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the SynchronisedEntityCore schema.
 */
export const CompiledSynchronisedEntityCore: ICompiledValidator = validate57;

/**
 * Compiled validator for the SyncChangeOperation schema.
 */
export const CompiledSyncChangeOperation: ICompiledValidator = validate55;

